// Entity names
string BEGGAR = "beggar";
string COG_KEY = "cog_key";
string COG_LOCKED = "cog_locked";
string INVENTOR_PANEL = "fs_door_wood_58";
string SHOP_BELL = "func_shaking_1";

void openGate(entity target, entity door, entity callscriptfunction)
{
    string keyName = door.getKey("used_by");
    entity key = sys.getEntity(keyName);
    $player1.replaceInvItem(key, $null_entity);
}

void frobCandlestick(entity ent)
{
	entity candle = ent.getBindMaster();
	candle.remove();

	frob_item(ent);
}

void removeAI()
{
    sys.getEntity(BEGGAR).remove();
}

void useCog(entity lock)
{
    entity cog = sys.getEntity(COG_KEY);
    entity cogLocked = sys.getEntity(COG_LOCKED);
    entity inventorPanel = sys.getEntity(INVENTOR_PANEL);

    $player1.replaceInvItem(cog, $null_entity);
    cogLocked.setOrigin('-2695.25 -553 491');
    lock.startSound("snd_unlock", SND_CHANNEL_UNUSED, false);
    inventorPanel.Open();
    inventorPanel.setFrobable(1);
}

/////////
// LIFT
/////////

// The fetch buttons target both the elevator and a atdm_target_callscriptfunction entity like so:
// The fetch button has a 'target' spawnarg which targets the elevator
// target0 targets the atdm_target_callscriptfunction
// the atdm_target_callscriptfunction calls this script, and targets the doors, and has 'foreach 1' set.
// The button also needs a spawnarg called position_entity_name whose value is the name of the multistate position entity
//
// The elevator needs to have the scriptobject spawnarg set to 'tdm_elevator'
//
// The multistate position entities need to target the doors, and set always_trigger_targets = 0

void controlLiftDoors(entity target, entity button, entity callscriptfunction)
{
    // The button that calls this is targeting the lift with 'target' spawnarg (i.e. not 'target0', 'target1', etc.)
    entity lift = button.getEntityKey("target");

    // Get the multistate position entity this button corresponds to
    // custom spawnarg: didn't want to use 'target' or 'position' because they activate unwanted functionality on some buttons
    entity multiStatePosition = button.getEntityKey("position_entity_name"); 

    // ensure the lift is idle and it's on the appropriate floor
    if ( !lift.isMoving() && (lift.getOrigin() == multiStatePosition.getOrigin()) )
    {
        if (target.IsOpen())
        {
            target.Close();
        }
        else
        {
            target.Open();
        }
    }
}

void takeBell()
{
    sys.getEntity(SHOP_BELL).remove();
}

void ringBell()
{
    entity shopBell = sys.getEntity(SHOP_BELL);
    if (shopBell)
    {
        sys.trigger($atdm_start_alarm_1);
        sys.trigger($func_shaking_1);
        sys.wait(3);
        sys.trigger($func_shaking_1);
    }
}

// main - keep at bottom
void main()
{
    sys.waitFrame();

    // stop the shop bell from shaking at map start
    sys.trigger(sys.getEntity(SHOP_BELL));
}